# Generated by Django 2.2.6 on 2020-08-17 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmnd', models.IntegerField(default=0, verbose_name='CMND')),
                ('username', models.CharField(max_length=50, verbose_name='Tên Khách Hàng')),
                ('phone', models.CharField(max_length=30, verbose_name='Số Điện Thoại')),
                ('number_ticket', models.IntegerField(default=0, verbose_name='Số Vé Mua')),
                ('number_ticket_go', models.IntegerField(default=0, verbose_name='Số Vé Đi')),
                ('number_ticket_return', models.IntegerField(default=0, verbose_name='Số Vé Về')),
                ('deposit', models.CharField(max_length=50, verbose_name='Tiền Đặt Cọc')),
                ('money', models.CharField(max_length=50, verbose_name='Tiền Còn Thiếu')),
                ('create_date', models.DateField(default=datetime.date.today, verbose_name='Ngày Nhập')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ngày Tàu Đi')),
                ('start_time_train', models.TimeField(blank=True, max_length=50, null=True, verbose_name='Giờ Đi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày Tàu Về')),
                ('end_time_train', models.TimeField(blank=True, max_length=50, null=True, verbose_name='Giờ Về')),
                ('note', models.TextField(max_length=2000, verbose_name='Ghi Chú')),
                ('status', models.IntegerField(choices=[(0, 'Vé Mới Đặt'), (1, 'Vé Đã Nhận'), (2, 'Vé Đã Đi'), (3, 'Vé Không Đi')], default=0, verbose_name='Trạng Thái')),
            ],
        ),
    ]
