# Generated by Django 2.2.6 on 2020-08-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idproject', models.IntegerField(default=0)),
                ('classname', models.CharField(max_length=255)),
                ('properties', models.TextField()),
                ('attributes', models.TextField()),
                ('lengths', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CRUD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateField(auto_created=True)),
                ('idproject', models.IntegerField(default=0)),
                ('idclass', models.IntegerField(default=0)),
                ('actiontype', models.CharField(max_length=10)),
                ('titles', models.TextField()),
                ('properties', models.TextField()),
                ('alias', models.TextField()),
                ('refers', models.TextField()),
                ('titlecreate', models.CharField(max_length=100)),
                ('titleupdate', models.CharField(max_length=100)),
                ('inputtypes', models.TextField()),
                ('validates', models.TextField()),
                ('formats', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
